# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.0.0
    hooks:
      - id: flakeheaven
        additional_dependencies:
          - flake8-print

  - repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
      - id: black

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
    hooks:
      - id: upgrade-type-hints

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.991'
#    hooks:
#      - id: mypy
#        args: [ --no-strict-optional, --ignore-missing-imports ]
